name: action-publish

on:
    workflow_dispatch:
    push:
        branches:
            - ipod_touch_1g

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: deps
              run: sudo apt-get install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build libsdl2-dev
            - name: build it lol
              run: mkdir build && cd build && CFLAGS=-Wno-error ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-pie --disable-slirp --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto' && make
            - uses: actions/upload-artifact@v2
              with:
                    name: build
                    path: ./build/arm-softmmu/qemu-system-arm
