name: action-publish

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Prepare building
              run: mkdir build
            - name: Prepare building 2
              run: cd build
            - name: Configure project
              run: ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-pie --disable-slirp --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'
            - name: go 
              run: make
